In [8]:
#Advance Concept

In [2]:
#insert the element into specific Position
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr)
new_arr=np.insert(arr,2,100)
print(new_arr)

[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]


In [3]:
# insert into 2D array
arr_2d=np.array([[1,2],[3,4]])
print(arr_2d)
#insert a new row at index 1
new_arr_2d=np.insert(arr_2d,1,[5,6],axis=0)   #Axis 0-row && Axis 1 -column
print(new_arr_2d)

[[1 2]
 [3 4]]
[[1 2]
 [5 6]
 [3 4]]


In [4]:
#Append
arr=np.array([10,20,30])
print(arr)
new=np.append(arr,[40,50,60])
print(new)

[10 20 30]
[10 20 30 40 50 60]


In [5]:
#concatenate
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
new_arr=np.concatenate((arr1,arr2))
print(new_arr)

[1 2 3 4 5 6]


In [6]:
#Removing elements of an array
#delete()
arr=np.array([10,20,30])
print(arr)
new_arr=np.delete(arr,0)
print(new_arr)

[10 20 30]
[20 30]


In [7]:
#Remove element from 2d array
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)
new=np.delete(arr_2d,0,axis=0)
print(new)

[[1 2 3]
 [4 5 6]]
[[4 5 6]]


In [9]:
#Stacking
#vstack()- row wise
#hstack()- column wise
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.vstack((arr1,arr2)))  #vertically stack
print(np.hstack((arr1,arr2)))  #horizontally stack

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [11]:
#splitting
""" np.split(arr,parts)- split into equal parts
np.hsplit()- horizontal split
np.vsplit()-vertical split"""
arr=np.array([1,2,3,4,5,6])
print(np.split(arr,2))

[array([1, 2, 3]), array([4, 5, 6])]


In [17]:
print(np.hsplit(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [29]:
arr=np.array([[1,2,3], #for vsplit need 2D array
             [4,5,6]])
print(np.vsplit(arr,1))

[array([[1, 2, 3],
       [4, 5, 6]])]
