In [1]:
import numpy as np
prices=np.array([100,200,300])
discount=10
final_prices=prices-(prices*discount/100)
print(final_prices)

[ 90. 180. 270.]


In [5]:
#Broadcasting using single element
arr=np.array([10,20,30,40])
res=arr*2
print(res)

[20 40 60 80]


In [3]:
#broadcasting of 1d to 2d array

In [4]:
matrix=np.array([[1,2,3],[4,5,6]])
vector=np.array([10,20,30])
res=matrix+vector
print(res)


[[11 22 33]
 [14 25 36]]
