In [ ]:
# Beginner Level

In [1]:
"""Create a 1D NumPy array of numbers from 0 to 9."""
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
""" Create a 3×3 NumPy array with all elements as True."""
arr=np.ones((3,3),dtype='bool')
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
#or
arr=np.full((3,3),True)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
"""Generate an array of 10 random integers between 1 and 100."""
arr=np.random.randint(1,101,size=10)
arr


array([74, 16, 16, 46, 53, 66, 33, 51, 37, 47], dtype=int32)

In [9]:
"""Create an array of 10 zeros and then replace the fifth element with 5."""
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
arr[4]=5

In [11]:
arr

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

In [16]:
"""Generate a sequence of even numbers from 2 to 20 using NumPy."""
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#Intermediate Level

In [17]:
"""Create a 4×4 identity matrix"""
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
"""Generate a 5×5 matrix with values from 1 to 25 arranged row-wise."""
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16],
              [17,18,19,20]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [22]:
""" Create two 1D arrays and perform element-wise addition, subtraction, multiplication, and division"""
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [24]:
arr2-arr1

array([5, 5, 5, 5, 5])

In [25]:
arr1*arr2

array([ 6, 14, 24, 36, 50])

In [26]:
arr1/arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [32]:
""" Find the maximum, minimum, and mean of a random 10-element array."""
arr1=np.random.rand(10)
max(arr1)

np.float64(0.8611450091110027)

In [33]:
min(arr1)

np.float64(0.08034892654028358)

In [34]:

arr1.mean()

np.float64(0.5350873390958384)

In [35]:
"""Reshape a 1D array of 16 elements into a 4×4 matrix."""
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
#Indexing & Slicing

In [39]:
"""Extract all odd numbers from a NumPy array."""
arr=np.array([1,2,3,4,5,6,7,8])
ind=[0,2,4,6]
arr[ind]


array([1, 3, 5, 7])

In [3]:
"""Reverse a NumPy array."""
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
arr[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [7]:
""" Extract the first column of a 2D array."""
arr=np.array([[1,2,3],[4,5,6]])
arr[0,0]

np.int64(1)

In [8]:
"""Get the diagonal elements of a matrix"""
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
             ])
diagonal=np.diagonal(arr)
diagonal

array([1, 5, 9])

In [9]:
"""Replace all odd numbers in an array with -1."""
arr=np.array([1,2,3,4,5,6,7,8])
arr[arr%2==1]=-1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8])

In [10]:
#Advanced Level

In [14]:
""" Stack two NumPy arrays vertically and horizontally"""
arr1=np.array([[1,2],
              [3,4]])
arr2=np.array([[5,6],
               [7,8]])
arr=np.vstack((arr1,arr2))
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
arr=np.hstack((arr1,arr2))
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [16]:
"""Create a 5×5 matrix and normalize it (scale values between 0 and 1)."""
import numpy as np

# create random 5x5 matrix
matrix = np.random.randint(1, 100, (5, 5))
print("Original Matrix:\n", matrix)

# normalize (0 to 1)
normalized = (matrix - matrix.min()) / (matrix.max() - matrix.min())
print("\nNormalized Matrix:\n", normalized)


Original Matrix:
 [[29 67 27  1 99]
 [20 89 89  5 68]
 [39 70 65 49 89]
 [60 11 85 56 60]
 [87 79 29 47 71]]

Normalized Matrix:
 [[0.28571429 0.67346939 0.26530612 0.         1.        ]
 [0.19387755 0.89795918 0.89795918 0.04081633 0.68367347]
 [0.3877551  0.70408163 0.65306122 0.48979592 0.89795918]
 [0.60204082 0.10204082 0.85714286 0.56122449 0.60204082]
 [0.87755102 0.79591837 0.28571429 0.46938776 0.71428571]]


In [18]:
"""Multiply a 3×3 matrix with another 3×3 matrix."""
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])
result=A*B

print(result)


[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [19]:
result = np.dot(A, B)
result

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [21]:
"""Compute the dot product of two vectors"""
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

dot_product = np.dot(v1, v2)

print(dot_product)


32


In [22]:
"""Find the eigenvalues and eigenvectors of a 2×2 matrix"""
import numpy as np

A = np.array([
    [4, 2],
    [1, 3]
])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:",eigenvalues)

print("\nEigenvectors:",eigenvectors)


Eigenvalues: [5. 2.]

Eigenvectors: [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [23]:
#Real-World Type

In [26]:
"""You have an array of student marks: [45, 67, 89, 34, 76, 92, 56, 78].
- Find the average marks.
- Get marks greater than 70.
- Replace all marks below 40 with 40."""
arr=np.array([45, 67, 89, 34, 76, 92, 56, 78])
#average
arr.mean()


np.float64(67.125)

In [30]:
#marks greater than 70
arr[arr>70]


array([89, 76, 92, 78])

In [31]:
#Replace all marks below 40 with 40
arr[arr<40]=40

In [32]:
arr

array([45, 67, 89, 40, 76, 92, 56, 78])

In [33]:
"""You have temperature readings in Celsius stored in an array. Convert them to Fahrenheit."""
import numpy as np

# Celsius temperatures
celsius = np.array([0, 20, 30, 37, 100])

# Convert to Fahrenheit
fahrenheit = (celsius * 9/5) + 32

print("Celsius:", celsius)
print("Fahrenheit:", fahrenheit)


Celsius: [  0  20  30  37 100]
Fahrenheit: [ 32.   68.   86.   98.6 212. ]


In [35]:
"""Given sales data for 12 months, find total, average, max, and min sales using NumPy functions."""
sales = np.array([12000, 15000, 17000, 16000, 18000, 20000,
                  22000, 21000, 19000, 23000, 25000, 24000])
#total
total=np.sum(sales)
print("Total=",total)

Total= 232000


In [37]:
#average
avg=np.mean(sales)
print("Average=",avg)

Average= 19333.333333333332


In [38]:
#max
max1=np.max(sales)
print("Maximum=",max1)

Maximum= 25000


In [40]:
#Min
min1=np.min(sales)
print("Minimum=",min1)

Minimum= 12000


In [41]:
"""Simulate rolling two dice 1000 times using NumPy and find the probability distribution of their
sums."""
import numpy as np

# Number of rolls
n = 1000

# Roll two dice
dice = np.random.randint(1, 7, size=(n, 2))

# Sum of dice
sums = dice.sum(axis=1)

# Count occurrences of each possible sum (0–12, we use 13 size)
counts = np.bincount(sums, minlength=13)

# Probability distribution (only sums 2–12 are valid)
probabilities = counts[2:13] / n

# Display results
for s, p in enumerate(probabilities, start=2):
    print(f"Sum = {s}, Probability = {p:.3f}")



Sum = 2, Probability = 0.017
Sum = 3, Probability = 0.058
Sum = 4, Probability = 0.083
Sum = 5, Probability = 0.108
Sum = 6, Probability = 0.143
Sum = 7, Probability = 0.192
Sum = 8, Probability = 0.155
Sum = 9, Probability = 0.103
Sum = 10, Probability = 0.075
Sum = 11, Probability = 0.042
Sum = 12, Probability = 0.024


In [42]:
""" Given two arrays of size 1000, compute their correlation coefficient."""
import numpy as np

# Create two arrays of size 1000 (example data)
x = np.random.rand(1000)
y = np.random.rand(1000)

# Correlation coefficient matrix
corr_matrix = np.corrcoef(x, y)

# Extract the correlation coefficient
correlation = corr_matrix[0, 1]

print("Correlation Coefficient:", correlation)


Correlation Coefficient: -0.014228065764669727
